### ISSUE TITLE
Swirl stopped working while loading "Exploratory Data Analysis" course

### ISSUE THREAD

**Issue by rishiayri** [swirldev/swirl#406] opened 2016-02-06 09:20 UTC
I installed course "Exploratory Data Analysis" from the swirl but I try to access the course it gives the following message and Swirl ends abruptly.

Selection: 1

| Attemping to load lesson dependencies...

| Package ‘ggplot2’ loaded correctly!

| Package ‘fields’ loaded correctly!

| Package ‘jpeg’ loaded correctly!

| Package ‘datasets’ loaded correctly!

Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

| Leaving swirl now. Type swirl() to resume.

Please advise.

**Comment by seankross** [comment] 2016-02-08 17:58
Hi @rishiayri,

Which lesson gives you this error?

**Comment by rishiayri** [comment] 2016-02-08 22:06
Hi,

"Exploratory Data Analysis", the first lesson in the course.

Rishi.

**Comment by seankross** [comment] 2016-02-09 18:54
Hi @rishiayri 

This is a duplicate of #384, see the conversation there for help and discussion.

**Closed by seankross** 2016-02-09 18:54 UTC

**Comment by rishiayri** [comment] 2016-02-10 10:06
HI,

I run the code mentioned in #384, uninstall the course and installed it again but I am still getting the same error message.

| Would you like to continue with one of these lessons?

1: Exploratory Data Analysis Hierarchical Clustering
2: Regression Models Introduction
3: Statistical Inference Probability2
4: No. Let me start something new.

Selection: 1

| Attemping to load lesson dependencies...

| Package ‘ggplot2’ loaded correctly!

| Package ‘fields’ loaded correctly!

| Package ‘jpeg’ loaded correctly!

| Package ‘datasets’ loaded correctly!

Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

**Comment by rishiayri** [comment] 2016-02-10 10:52
I am enrolled in the Data Science specialization and the Swirl exercises helps a lot in understanding the concepts in a practical way.
Can you help in resolving the issue ASAP.
Let me know if I am not following the steps correctly.

**Comment by seankross** [comment] 2016-02-10 17:42
@rishiayri I just made a suggestion in #384. Please make comments reated to this issue there from now on.
