### ISSUE TITLE
Answer matcher should accept directory names followed by slash

### ISSUE THREAD

**Issue by reitzig** [swirldev/swirl#403] opened 2016-02-01 14:49 UTC
When I run swirl in RStudio, tab-completion will give be e.g.

```R
unlink("testdir/")
```

In lesson 2, this is not recognized as a valid answer -- it insists on `unlink("testdir")` (despite the tab-completed version working as intended).

**Comment by seankross** [comment] 2016-02-08 18:24
This lesson is broken, it will be overhauled soon. I'm going to close this issue because it's a duplicate of other problems with this lesson.

**Closed by seankross** 2016-02-08 18:24 UTC
