### ISSUE TITLE
Kicked out of R Swirl for 'permission denied'

### ISSUE THREAD

**Issue by lejanco** [swirldev/swirl#400] opened 2016-01-25 03:36 UTC
Hello,

I was working on Probability1 and received the following message:

Now we'll apply the concepts of probability to playing
| cards.

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning messages:
1: In file.create(to[okay]) :
  cannot create file 'cards.R', reason 'Permission denied'
2: In file(filename, "r", encoding = encoding) :
  cannot open file 'cards.R': Permission denied

Any suggestions on how to fix this other than run as an administrator? Thank you.

**Comment by seankross** [comment] 2016-01-25 17:45
Hi @lejanco,

Unfortunately this looks like an issue with permissions, which means you would need to run R or RStudio as an administrator. We're working on a fix for this kind of problem but it isn't ready yet.

Sean

**Comment by reitzig** [comment] 2016-02-01 13:56
> would need to run R or RStudio as an administrator

Oh no, please don't! I'm on GNU/Linux, and this should *not* be the answer!

It should be possible to run swirl from out of user space (say, `/usr/...`). It should then put its data into `~/.R/swirl/...` or something.

**Comment by seankross** [comment] 2016-02-08 17:51
Hi @reitzig,

The next version of swirl will be able to operate entirely in user space. Running RStudio as administrator is just usually the easiest thing to do for Windows users.

**Comment by reitzig** [comment] 2016-02-09 08:17
@seankross  Great, thanks!
(I have noticed that many things in R(Studio) are Windows-flavored, but running user stuff as root is a big no-no.)

**Comment by blurredHorizon** [comment] 2016-02-21 07:30
I'm glad I found this thread.  My R installation works fine until I need to use Swirl, because it must be used as a superuser.  What further complicates my use case is that I like to run R on a server.  This means that when I use Swirl, I must SSH into the server so I can run "Sudo R."  I don't like this but it does the job.  Except when a module needs R Studio because of graphical output.  This makes SSH insufficient to complete those modules, and I don't want to even try to give R Studio Server admin access.  So, I have a duplicated install of R on another computer for the sole purpose of using Swirl.

I think it would be a nice improvement to allow standard users to have the needed permissions to run Swirl.  Thanks for considering this!

**Comment by seankross** [comment] 2016-02-29 16:47
Hi @blurredHorizon, if you want to try a version of swirl that *should* operate completely in user space you can install the dev version of swirl which is stable:

```r
library(devtools)
install_github("swirldev/swirl", ref = "dev")
```

Running swirl in user space requires a little setup:

```r
library(swirl)
swirl_options(swirl_courses_dir = "[some/path]")
swirl_options(swirl_data_dir = "[some/other/path]")
```
If you run into an issue please let me know!

**Comment by popoff1998** [comment] 2016-04-04 11:48
Hi.
I'm trying your solution with dev version to use swirl in user space because my users haven't rigths to write in R directory.

tried this:
(in the shell)
mkdir -p ~/SWIRL/COURSES
mkdir ~/SWIRL/DATA

(inside R)
library(swirl)
swirl_options(swirl_courses_dir = "~/SWIRL/COURSES")
swirl_options(swirl_data_dir = "~/SWIRL/DATA")

I tried with the course "Regression_models". The course downloads OK, I can start it but selecting the Introduction, swirl throws this message:

"Unable to open /usr/local/lib/R/library/swirl/Courses/Regression_Models/Introduction/galton.csv"

This file is in "~/SWIRL/COURSES//Regression_Models/Introduction/galton.csv" but it seems that swirl only use swirl_courses_dir to download the course and not to play it.

Regards.

**Comment by popoff1998** [comment] 2016-04-04 19:30
Hmm ...
 I see thet the problem isn't with swirl, the problem is in the own course code. The file swirl_courses/Regression_Models/Introduction/initLesson.R has this code:

```
# Put initialization code in this file.
galton <- read.csv(file.path(find.package("swirl"), "Courses/Regression_Models/Introduction", "galton.csv"))
```
So, if the course isn't installed in swirl package dir, the file galton.csv is not found. This is so bad because all attemps to make swirl to work in user space require a rewrite of thimgs like this in all courses ...

**Comment by seankross** [comment] 2016-04-05 17:05
@popoff1998 This will be fixed by 5pm EDT for all courses.

**Comment by seankross** [comment] 2016-04-05 22:09
@popoff1998 Let me know if reinstalling the course fixes your issue.

**Comment by popoff1998** [comment] 2016-04-06 07:13
Thanks for the updates.

But after deleting the course in my home dir and reinstall the course, the error is the same because the code in initLesson.R is the same.

It seems that the github repository is updates with the changes but the Regression_Models.swc file isn't updated.

**Comment by seankross** [comment] 2016-04-06 16:21
@popoff1998, you're right, let me try that again.

**Closed** 2016-04-06 19:48 UTC

**Comment by seankross** [comment] 2016-04-06 19:57
@popoff1998 This should now be fixed. Please let me know if you're still having issues.

**Comment by popoff1998** [comment] 2016-04-07 18:31
I can confirm you that now it's ok.

Many thanks.

**Comment by sbcalaff** [comment] 2016-04-14 11:09
It still does not work. You need a parenthesis:

Before:
`file.copy(from=file.path(file.path(.get_course_path(),
	"Regression_Models","MultiVar_Examples3","hunger.csv"),
          to="hunger.csv")`

After:
`file.copy(from=file.path(file.path(.get_course_path(),
	"Regression_Models","MultiVar_Examples3","hunger.csv")),
          to="hunger.csv")`

With this parenthesis, now it works.

**Comment by seankross** [comment] 2016-04-15 01:01
@sbcalaff just fixed this, thanks again for the PR.
