### ISSUE TITLE
qplot does not recognize the 'method' arguement

### ISSUE THREAD

**Issue by rheplo** [swirldev/swirl#401] opened 2016-01-29 19:30 UTC
When I try to input the correct function call of qplot in section 9 of Exploratory Data Analysis I receive this error:

Error: Unknown parameters: method

| Leaving swirl now. Type swirl() to resume.

**Comment by sloisellegd** [comment] 2016-02-07 19:48
This issue is a duplicate of this:
https://github.com/swirldev/swirl_courses/issues/224

**Comment by seankross** [comment] 2016-02-08 18:32
You can find work arounds in the issue above or you can try this: http://seankross.com/rbootcamp/hw2.html

Closing because this is a duplicate.

**Closed by seankross** 2016-02-08 18:32 UTC
