### ISSUE TITLE
Unable to run swirl()

### ISSUE THREAD

**Issue by tklebel** [swirldev/swirl#429] opened 2016-03-18 11:14 UTC
``` r
library(swirl)
#> | Hi! Type swirl() when you are ready to begin.

swirl()
#> Error in match.arg(type, c("success", "failure", "error", "skip", "warning")) : 
#>   'arg' must be NULL or a character vector

#> | Leaving swirl now. Type swirl() to resume.
```

My SessionInfo:

``` r
devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.2.4 (2016-03-10)
#>  system   x86_64, darwin13.4.0        
#>  ui       RStudio (0.99.891)          
#>  language (EN)                        
#>  collate  de_AT.UTF-8                 
#>  tz       Europe/Vienna               
#>  date     2016-03-18
#> Packages ------------------------------------------------------------------
#>  package    * version     date       source                          
#>  bitops       1.0-6       2013-08-17 CRAN (R 3.2.0)                  
#>  clipr        0.2.0       2015-10-06 CRAN (R 3.2.0)                  
#>  crayon       1.3.1       2015-07-13 CRAN (R 3.2.0)                  
#>  devtools     1.10.0.9000 2016-03-08 Github (hadley/devtools@b6a23be)
#>  digest       0.6.9       2016-01-08 CRAN (R 3.2.3)                  
#>  evaluate     0.8.3       2016-03-05 CRAN (R 3.2.4)                  
#>  formatR      1.3         2016-03-05 CRAN (R 3.2.4)                  
#>  htmltools    0.3         2015-12-29 CRAN (R 3.2.3)                  
#>  httr         1.1.0       2016-01-28 CRAN (R 3.2.3)                  
#>  knitr        1.12.3      2016-01-22 CRAN (R 3.2.3)                  
#>  magrittr     1.5         2014-11-22 CRAN (R 3.2.0)                  
#>  memoise      1.0.0       2016-01-29 CRAN (R 3.2.3)                  
#>  R6           2.1.2       2016-01-26 CRAN (R 3.2.3)                  
#>  RCurl        1.95-4.8    2016-03-01 CRAN (R 3.2.4)                  
#>  reprex       0.0.0.9001  2015-09-26 Github (jennybc/reprex@1d6584a) 
#>  rmarkdown    0.9.5       2016-02-22 CRAN (R 3.2.3)                  
#>  rstudioapi   0.5         2016-01-24 CRAN (R 3.2.3)                  
#>  stringi      1.0-1       2015-10-22 CRAN (R 3.2.0)                  
#>  stringr      1.0.0       2015-04-26 Github (hadley/stringr@28b327c) 
#>  swirl      * 2.2.21      2015-01-04 CRAN (R 3.2.0)                  
#>  testthat     0.11.0.9000 2016-03-12 Github (hadley/testthat@a102b89)
#>  withr        1.0.1       2016-02-04 CRAN (R 3.2.3)                  
#>  yaml         2.1.13      2014-06-12 CRAN (R 3.2.0)
```

**Comment by seankross** [comment] 2016-03-18 14:02
`install.packages("testthat")` should fix this error.

**Comment by tklebel** [comment] 2016-03-19 09:28
thx!

**Comment by prince1809** [comment] 2016-04-14 14:08
`> swirl()`
`Error in match.arg(type, c("success", "failure", "error", "skip", "warning")) : `
`  'arg' must be NULL or a character vector`

`| Leaving swirl now. Type swirl() to resume.`

`install.packages("testthat") ` couldn't solve the problem.


```
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.0

loaded via a namespace (and not attached):
 [1] httr_1.1.0      magrittr_1.5    R6_2.1.2        tools_3.2.4     RCurl_1.95-4.8  curl_0.9.7      yaml_2.1.13     memoise_1.0.0   crayon_1.3.1    stringi_1.0-1  
[11] stringr_1.0.0   digest_0.6.9    testthat_0.11.0 bitops_1.0-6 
```

**Comment by pkopac** [comment] 2016-04-14 14:32
I confirm the same problem on Ubuntu Linux. The suggested solution didn't work.
```
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, linux-gnu                          
 ui       RStudio (0.99.893)                         
 language en_US                                      
 collate  en_US.UTF-8                                
 tz       <NA>                                       
 date     2016-04-14                                 

Packages -----------------------------------------------------------------------------------------------------------------------------------
 package  * version  date       source        
 bitops     1.0-6    2013-08-17 CRAN (R 3.2.4)
 crayon     1.3.1    2015-07-13 CRAN (R 3.2.4)
 devtools   1.11.0   2016-04-12 CRAN (R 3.2.4)
 digest     0.6.9    2016-01-08 CRAN (R 3.2.4)
 httr       1.1.0    2016-01-28 CRAN (R 3.2.4)
 magrittr   1.5      2014-11-22 CRAN (R 3.2.4)
 memoise    1.0.0    2016-01-29 CRAN (R 3.2.4)
 R6         2.1.2    2016-01-26 CRAN (R 3.2.4)
 RCurl      1.95-4.8 2016-03-01 CRAN (R 3.2.4)
 stringi    1.0-1    2015-10-22 CRAN (R 3.2.4)
 stringr    1.0.0    2015-04-30 CRAN (R 3.2.4)
 swirl    * 2.4.0    2016-03-25 CRAN (R 3.2.4)
 testthat   1.0.0    2016-04-14 CRAN (R 3.2.4)
 withr      1.0.1    2016-02-04 CRAN (R 3.2.4)
 yaml       2.1.13   2014-06-12 CRAN (R 3.2.4)

> options(error = function() traceback(2))
> swirl()
Error in match.arg(type, c("success", "failure", "error", "skip", "warning")) : 
  'arg' must be NULL or a character vector
7: stop("'arg' must be NULL or a character vector")
6: match.arg(type, c("success", "failure", "error", "skip", "warning"))
5: expectation(identical(uses, TRUE), str_c("does not use ", label))
4: uses_func("info")(e$expr)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)

| Leaving swirl now. Type swirl() to resume.
```

**Comment by seankross** [comment] 2016-04-14 14:37
I'm working on fixing this issue now.

**Comment by schwab** [comment] 2016-04-14 14:48
Thanks for looking into this problem Sean. I'm getting the same issue as well for a Coursera class and found this thread while searching for a solution.  If you need any further details, I've subscribed to notifications here and can reproduce it currently.

**Comment by seankross** [comment] 2016-04-14 15:28
Temporary workaround:

```r
install.packages("ghit")
library(ghit)
install_github("swirldev/swirl[stable]")
library(swirl)
swirl()
```

I'm working on a permanent solution that will be released as quickly as possible.

**Comment by prince1809** [comment] 2016-04-14 15:35
Thank you

It worked

**Comment by schwab** [comment] 2016-04-14 17:15
Also verified this work-around corrected it for me on Ubuntu 15.10.  Thanks for getting it out there so fast!

**Comment by seankross** [comment] 2016-04-15 00:04
Please download the latest version of swirl with `install.packages("swirl")`. This should resolve the issue. Make sure your installed version of swirl is 2.4.1 or later.

**Closed by seankross** 2016-04-15 00:04 UTC

**Comment by jarturomora** [comment] 2016-04-17 11:13
Dear @seankross thanks for your effort solving this problem and for your great contribution to spread the R Language learning. Now my swirl installation is working.

**Comment by dasmoocher** [comment] 2016-04-21 20:20
I'm having the same issue in the Functions tutorial:

| The last R expression to be evaluated in a function will become the return value of that function. We want this function to take one
| argument, x, and return x without modifying it. Delete the pound sign so that x is returned without any modification. Make sure to save
| your script before you type submit().

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

I tried the "testthat" package, restarting RStudio. and reinstalling swirl.
Also ran the temp fix:
install.packages("ghit")
library(ghit)
install_github("swirldev/swirl[stable]")
library(swirl)
swirl()

Windows 7 Enterprise, SP-1. 64-bit
Session info ------------------------------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, mingw32                            
 ui       RStudio (0.99.893)                         
 language (EN)                                       
 collate  English_United States.1252                 
 tz       America/New_York                           
 date     2016-04-21                                 

Packages ----------------------------------------------------------------------------------------------------------------------------------
 package      * version  date       source        
 Biobase      * 2.30.0   2015-10-14 Bioconductor  
 BiocGenerics * 0.16.1   2015-11-06 Bioconductor  
 Biostrings   * 2.38.4   2016-02-09 Bioconductor  
 bitops         1.0-6    2013-08-17 CRAN (R 3.2.3)
 crayon         1.3.1    2015-07-13 CRAN (R 3.2.4)
 curl           0.9.7    2016-04-10 CRAN (R 3.2.4)
 devtools       1.11.0   2016-04-12 CRAN (R 3.2.5)
 digest         0.6.9    2016-01-08 CRAN (R 3.2.4)
 ghit         * 0.2.5    2016-03-15 CRAN (R 3.2.5)
 git2r          0.14.0   2016-03-13 CRAN (R 3.2.4)
 httr           1.1.0    2016-01-28 CRAN (R 3.2.4)
 IRanges      * 2.4.8    2016-02-26 Bioconductor  
 magrittr       1.5      2014-11-22 CRAN (R 3.2.4)
 memoise        1.0.0    2016-01-29 CRAN (R 3.2.4)
 R6             2.1.2    2016-01-26 CRAN (R 3.2.4)
 RCurl          1.95-4.8 2016-03-01 CRAN (R 3.2.3)
 rsconnect      0.4.2.1  2016-03-30 CRAN (R 3.2.5)
 S4Vectors    * 0.8.11   2016-01-29 Bioconductor  
 stringi        1.0-1    2015-10-22 CRAN (R 3.2.3)
 stringr        1.0.0    2015-04-30 CRAN (R 3.2.4)
 swirl        * 2.4.1    2016-04-21 local         
 testthat       1.0.0    2016-04-14 CRAN (R 3.2.5)
 withr          1.0.1    2016-02-04 CRAN (R 3.2.4)
 XVector      * 0.10.0   2015-10-14 Bioconductor  
 yaml           2.1.13   2014-06-12 CRAN (R 3.2.4)
 zlibbioc       1.16.0   2015-10-14 Bioconductor

**Comment by seankross** [comment] 2016-04-21 20:23
@dasmoocher see #434

**Comment by dasmoocher** [comment] 2016-04-21 20:31
@seankross Cool. Looks like that worked. Thank you.
