### ISSUE TITLE
Swirl not working as expected in Rstudio!

### ISSUE THREAD

**Issue by vijethrprasad** [swirldev/swirl#291] opened 2015-05-07 03:53 UTC
Hi, I'm new to R world. I have downloaded R and Rstudio and installed them. I'm tred to install swirl using R console. It kepp throwing errors , While midst of this I discovered I need to set Cran mirror. I set India as Cran mirror. Then ran install.packages("swirl"). Install was successful.Then I installed dependent packages RCurl,testthat and bitops using install.packages(). It works now.But When I try the same in Rstudio. It isn't working. I'm not sure how to set Cran Mirrror in RStudio also when I install packages, It says it is successful but when I run library("swirl") it again says dependent packages not found.
Below is the error msg:

package ‘bitops’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘bitops’
package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘RCurl’

The downloaded binary packages are in
	C:\Users\Vijeth\AppData\Local\Temp\Rtmpob3h42\downloaded_packages
> library("swirl")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘RCurl’
Error: package or namespace load failed for ‘swirl’

What is it that I'm doing wrong? Please help

**Comment by seankross** [comment] 2015-05-07 04:00
Looks like you don't have RCurl installed. Try:

```
install.packages("RCurl")
library(swirl)
```

**Comment by tribhuwan396** [comment] 2015-07-05 19:02
R curl is not supported in version 3.2.1. swirl is not installing for me too.

**Comment by seankross** [comment] 2015-07-07 14:24
Try the following:
```
install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
```

**Comment by tribhuwan396** [comment] 2015-07-07 16:58
I tried to do the same but the error is still occurring. The following is
the error which is coming:

> install.packages("swirl", repos="http://cran.rstudio.com",dependencies =
TRUE)
Installing package into ‘C:/Users/mukesh/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘RCurl’


  There is a binary version available but the source version is later:
        binary   source needs_compilation
RCurl 1.95-4.6 1.95-4.7              TRUE

  Binaries will be installed
trying URL '
http://cran.rstudio.com/bin/windows/contrib/3.2/RCurl_1.95-4.6.zip'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL '
http://cran.rstudio.com/bin/windows/contrib/3.2/RCurl_1.95-4.6.zip'
Warning in install.packages :
  download of package ‘RCurl’ failed
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.2.21.zip
'
Content type 'application/zip' length 132487 bytes (129 KB)
downloaded 129 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\mukesh\AppData\Local\Temp\RtmpU3zVF4\downloaded_packages

On Tue, Jul 7, 2015 at 7:54 PM, Sean Kross <notifications@github.com> wrote:

> Try the following:
>
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl/issues/291#issuecomment-119220446>.
>



-- 
Regards,
Tribhuwan Punetha
Member, Geeta Club
K J Somaiya Institute of Management Studies & Research

**Comment by seankross** [comment] 2015-07-07 17:55
What do you get from the result of:
```
cat(R.version.string)
```

**Comment by tribhuwan396** [comment] 2015-07-07 17:57
cat(R.version.string)
R version 3.2.1 (2015-06-18)

On Tue, Jul 7, 2015 at 11:25 PM, Sean Kross <notifications@github.com>
wrote:

> What do you get from the result of:
>
> cat(R.version.string)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl/issues/291#issuecomment-119283382>.
>



-- 
Regards,
Tribhuwan Punetha
Member, Geeta Club
K J Somaiya Institute of Management Studies & Research

**Comment by seankross** [comment] 2015-07-07 18:19
What operating system are you using?

**Comment by tribhuwan396** [comment] 2015-07-07 18:23
Windows 7

**Comment by seankross** [comment] 2015-07-07 18:43
It looks like you can't get the binaries for some reason, try compiling from source with:
```
install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")
```

**Comment by tribhuwan396** [comment] 2015-07-07 18:58
It shows the following message:
> install.packages("swirl", repos="http://cran.rstudio.com/",
dependencies=TRUE, type="source")
Installing package into ‘C:/Users/mukesh/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘RCurl’

trying URL 'http://cran.rstudio.com/src/contrib/RCurl_1.95-4.7.tar.gz'
Content type 'application/x-gzip' length 916897 bytes (895 KB)
downloaded 895 KB

trying URL 'http://cran.rstudio.com/src/contrib/swirl_2.2.21.tar.gz'
Content type 'application/x-gzip' length 51037 bytes (49 KB)
downloaded 49 KB

* installing *source* package 'RCurl' ...
** package 'RCurl' successfully unpacked and MD5 sums checked
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'RCurl'
* removing 'C:/Users/mukesh/Documents/R/win-library/3.2/RCurl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l
"C:\Users\mukesh\Documents\R\win-library\3.2"
C:\Users\mukesh\AppData\Local\Temp\Rtmpc7GFbh/downloaded_packages/RCurl_1.95-4.7.tar.gz'
had status 1
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status
ERROR: dependency 'RCurl' is not available for package 'swirl'
* removing 'C:/Users/mukesh/Documents/R/win-library/3.2/swirl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l
"C:\Users\mukesh\Documents\R\win-library\3.2"
C:\Users\mukesh\AppData\Local\Temp\Rtmpc7GFbh/downloaded_packages/swirl_2.2.21.tar.gz'
had status 1
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
‘C:\Users\mukesh\AppData\Local\Temp\Rtmpc7GFbh\downloaded_packages’

I can't understand the meaning of the above status. please help.

On Wed, Jul 8, 2015 at 12:13 AM, Sean Kross <notifications@github.com>
wrote:

> It looks like you can't get the binaries for some reason, try compiling
> from source with:
>
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl/issues/291#issuecomment-119299182>.
>



-- 
Regards,
Tribhuwan Punetha
Member, Geeta Club
K J Somaiya Institute of Management Studies & Research

**Comment by seankross** [comment] 2015-07-07 19:13
Is this your personal computer or a computer you're using at work? Are you behind any firewalls or proxies?

**Comment by tribhuwan396** [comment] 2015-07-07 19:16
This is my personal laptop using at my home. No

**Comment by seankross** [comment] 2015-07-07 19:30
I'm trying to think of a more elegant solution, but in the mean time try downloading RCurl from here: http://cran.r-project.org/bin/windows/contrib/3.2/RCurl_1.95-4.7.zip and you can follow installation instructions from this guide: http://outmodedbonsai.sourceforge.net/InstallingLocalRPackages.html

Sorry this hasn't gone smoothly.

**Comment by Dimagithub** [comment] 2015-07-11 20:32
I had same problem...the cause was that my CRAN mirror was blank for some reason. Once I changed it to one of the US sites - everything installed. 

To change it - go to Tools/Options/Packages

Hope this helps.

**Comment by robertmorrispainter** [comment] 2015-08-05 02:11
Hey - I`m a newbie too and I can`t download Swirl either. I am working on Linux Mint Rafeala machine at home. I get the following errors when attempting to "install.packages". When I try to install 'swirl' it says I need " stringi, httr, stringr and swirl" and any of these installs finishes with something similar if not exactly the same as the following  -

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /usr/lib/R
checking for R... /usr/lib/R/bin/R
checking for R >= 3.1.0... no
*** disabling C++11 use
checking for cat... /bin/cat
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... g++ -E
configure: error: in `/tmp/RtmpsK1KTj/R.INSTALL5c4c2aa3ddbf/stringi':
configure: error: C preprocessor "g++ -E" fails sanity check
See `config.log' for more details
ERROR: configuration failed for package ‘stringi’
* removing ‘/home/rob/R/i686-pc-linux-gnu-library/3.0/stringi’


Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status

Thanks - any ideas appreciated.

**Comment by seankross** [comment] 2015-08-09 12:11
Hi @robertmorrispainter I'm not too familiar with Linux Mint, but since it's Debian based perhaps this guide will help: https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux

**Comment by shwetamrit** [comment] 2016-02-10 16:11
Hi,i am also not able to load swirl,plz help me.

install.packages("swirl", dependencies=TRUE)
Installing package into ‘C:/Users/Shweta/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132378 bytes (129 KB)
downloaded 129 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\Shweta\AppData\Local\Temp\Rtmpsngb6l\downloaded_packages

library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
there is no package called ‘R6’
Error: package or namespace load failed for ‘swirl’
install.packages("evaluate")
Installing package into ‘C:/Users/Shweta/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

**Comment by shwetamrit** [comment] 2016-02-10 18:13
hi @seankross ,i tried but not working.

install.packages("R6")
Installing package into ‘C:/Users/Shweta/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/R6_2.1.2.zip'
Content type 'application/zip' length 271184 bytes (264 KB)
downloaded 264 KB

package ‘R6’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Shweta\AppData\Local\Temp\RtmpQ7YPCc\downloaded_packages
> swirl()
Error: could not find function "swirl"

**Comment by seankross** [comment] 2016-02-10 18:17
@shwetamrit 

Try:

```r
library(swirl)
swirl()
```

**Comment by shwetamrit** [comment] 2016-02-11 03:15
hi @seankross  its not working
 library(swirl)
Error in library(swirl) : there is no package called ‘swirl’
> swirl()
Error: could not find function "swirl"
>

**Comment by seankross** [comment] 2016-02-11 15:16
@shwetamrit 

Is swirl installed? You can check with `packageVersion("swirl")` and you can reinstall it with `install.packages("swirl")`.

**Comment by shwetamrit** [comment] 2016-02-13 12:49
Thank u for your support, finally swirl is working.
Thanks alot .

**Closed** 2016-02-13 18:10 UTC

**Comment by sahil-01** [comment] 2019-09-19 08:04
hi there,i have tried all the above mentioned things to fix the problem but i am still unable to install swirl.. For the record when i first tried to install swirl there were two options asking for permission like y/n ? and i accidently typed n for both of them and a now that options are not coming again,i tried everything even i reinstalled r and r studio but not working..i have r version 3.3.3 and operating system i am using is mac version 10.10.5.. please help and thankyou in advance.Here are the errors which i get when i try to install swirl. 
> install.packages("swirl")
also installing the dependency ‘stringr’


  There are binary versions available but the source versions
  are later:
        binary source needs_compilation
stringr  1.2.0  1.4.0             FALSE
swirl    2.4.3  2.4.4             FALSE

installing the source packages ‘stringr’, ‘swirl’

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.4.0.tar.gz'
Content type 'application/x-gzip' length 135777 bytes (132 KB)
==================================================
downloaded 132 KB

trying URL 'https://cran.rstudio.com/src/contrib/swirl_2.4.4.tar.gz'
Content type 'application/x-gzip' length 108533 bytes (105 KB)
==================================================
downloaded 105 KB

* installing *source* package ‘stringr’ ...
** package ‘stringr’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘stringi.so’ not found
ERROR: lazy loading failed for package ‘stringr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/stringr’
Warning in install.packages :
  installation of package ‘stringr’ had non-zero exit status
ERROR: dependency ‘stringr’ is not available for package ‘swirl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/swirl’
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/j3/qrl4hsn50vqf7d0kclghzmlm0000gn/T/RtmpHRDalf/downloaded_packages’
