### ISSUE TITLE
Issue with installing Swirl

### ISSUE THREAD

**Issue by naanaan** [swirldev/swirl#676] opened 2018-01-30 11:38 UTC
Hello!

I've been trying to install swirl several times on Mac OSX and just couldn't install 'digest'. Your help is much appreciated!

> install.packages("swirl")
also installing the dependency 'digest'
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  download of package 'digest' failed
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/swirl_2.4.3.tgz'
Content type 'application/x-gzip' length 237496 bytes (231 KB)
==================================================
downloaded 231 KB
tar: Failed to set default locale
The downloaded binary packages are in
	/var/folders/76/lswcntxs1s93n9wb59y9xzcw0000gn/T//RtmptvgWTz/downloaded_packages
> install.packages("digest")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  download of package 'digest' failed

**Comment by seankross** [comment] 2018-01-30 17:58
Duplicate of #675

**Closed by seankross** 2018-01-30 17:58 UTC
